language: cpp

compiler:
  - clang
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.2"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8"; fi


before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - cd ../bin
  - ./Test

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.8
            - g++-5.2
